project:
  type: website
  output-dir: docs # for GitHub Pages
  preview:
    port: 2025

website:
  title: 
    "Stefan Behrens | Mathematician | Deep Learner"
  favicon: images/favicon2.png
  site-url: https://www.sbehrens4d.com
  navbar:
    search: false
    right:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: math.qmd
        text: Math/Research
      - href: projects.qmd
        text: Code/Projects
      - href: blog.qmd
        text: Blog
      - sidebar:links
      - icon: github
        href: https://github.com/SB4D
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/sbehrens4d
        target: _blank
  sidebar: 
    - id: links
      title: Links
      style: docked
      contents: 
        - text: "**Google Scholar** — publications and citations"
          href: https://scholar.google.com/citations?user=qXTl8PEAAAAJ
          target: _blank
        - text: "**zbMath** — publications, citations, and reviews"
          href: https://zbmath.org/authors/behrens.stefan
          target: _blank
        - text: "**ar$\\chi$iv** — preprints"
          href: https://arxiv.org/a/behrens_s_1.html
          target: _blank
  page-footer:
    center: |
      © 2025 Stefan Behrens | 
      Content licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)  
      Code licensed under the [MIT License](https://opensource.org/licenses/MIT)
  draft-mode: gone

format:
  html:
    link-external-newwindow: true
    toc: true
    theme:
      - flatly
      # light: flatly
      # dark: darkly
    css: styles.css
    max-width: 800px
    # highlight-style: atom-one
    highlight-style: tango
    embed-resources: false
    include-in-header: _tools/sb4dlatex.html

# editor:
#   render-on-save: true
